# Generated by Django 6.0.1 on 2026-02-11 11:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Martyr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('biography', models.TextField()),
                ('summary', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='martyrs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'])])),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_martyrdom', models.DateField()),
                ('place_of_martyrdom', models.CharField(blank=True, max_length=200, null=True)),
                ('age_at_martyrdom', models.IntegerField(blank=True, null=True)),
                ('circumstances', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='martyrs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Martyr',
                'verbose_name_plural': 'Martyrs',
                'ordering': ['-date_of_martyrdom', 'full_name'],
                'indexes': [models.Index(fields=['is_active', 'date_of_martyrdom'], name='martyrs_mar_is_acti_36b536_idx'), models.Index(fields=['date_of_martyrdom'], name='martyrs_mar_date_of_29c1c8_idx'), models.Index(fields=['place_of_martyrdom'], name='martyrs_mar_place_o_4427fb_idx')],
            },
        ),
    ]
